// Hendelsesbanken for Tidslinjen.
// 135 vanlige kort og ett sjeldent bonuskort. Bok- og forslagsreferanser er lagret på tilknyttede kort.
// difficulty: 1 = lett, 2 = middels, 3 = vanskelig.

window.TIMELINE_EVENTS = [
  {"id":"knossos-palass-ca-1900-fkr","bankId":"TWH11","year":-1900,"displayYear":"ca. 1900 f.Kr.","title":"Det første palasset i Knossos bygges","difficulty":2,"category":"Arkitektur","period":"Oldtiden","region":"Kreta","emoji":"🏛️","image":"","info":"Et stort palassanlegg vokste fram i Knossos på Kreta. Palasset hadde rom for lagring, administrasjon og seremonier og ble et viktig sentrum i det minoiske samfunnet.","tags":["Arkitektur","Kreta","bronsealder"],"sourceLabel":"Foundation of the Hellenic World; Timelines of World History (2002), s. 31","sourceUrl":"https://www.fhw.gr/chronos/02/crete/en/habitance/palaces.html","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[31],"pdfPages":[35],"note":"Boka bruker ca. 2000 f.Kr.; kontrollkilden daterer de første minoiske palassene til ca. 1900 f.Kr."}],"skipYearGuess":true},
  {"id":"poverty-point-ca-1700-fkr","bankId":"TWH12","year":-1700,"displayYear":"ca. 1700 f.Kr.","title":"Monumentanlegget Poverty Point vokser fram","difficulty":3,"category":"Samfunn","period":"Oldtiden","region":"Nord-Amerika","emoji":"🏞️","image":"","info":"Jegere, fiskere og sankere bygde store jordvoller og hauger i dagens Louisiana. Poverty Point viser at også samfunn uten jordbruk kunne organisere omfattende byggearbeid og handel.","tags":["Samfunn","Nord-Amerika","bronsealder"],"sourceLabel":"UNESCO; Timelines of World History (2002), s. 33","sourceUrl":"https://whc.unesco.org/en/list/1435/","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[33],"pdfPages":[37],"note":"Boka oppgir etablering ca. 1100 f.Kr. UNESCO daterer byggingen til 1700–1100 f.Kr.; kortet gjelder begynnelsen av denne perioden."}],"skipYearGuess":true},
  {"id":"olmekisk-kultur-ca-1400-fkr","bankId":"TWH13","year":-1400,"displayYear":"ca. 1400 f.Kr.","title":"Den olmekiske kulturen vokser fram","difficulty":2,"category":"Kultur","period":"Oldtiden","region":"Mexico","emoji":"🗿","image":"","info":"Ved Mexicogolfen utviklet olmekiske samfunn seremonielle sentre og vidstrakte handelsforbindelser. De er blant annet kjent for store steinhoder og kunst som fikk innflytelse i Mesoamerika.","tags":["Kultur","Mexico","bronsealder"],"sourceLabel":"Brooklyn Museum; Timelines of World History (2002), s. 33","sourceUrl":"https://www.brooklynmuseum.org/opencollection/objects/5084","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[33],"pdfPages":[37],"note":"Boka bruker ca. 1200 f.Kr. Brooklyn Museum daterer den olmekiske sivilisasjonen til ca. 1400–400 f.Kr.; kortet bruker periodens omtrentlige start."}],"skipYearGuess":true},
  {"id":"akhenaton-amarna-ca-1347-fkr","bankId":"TWH14","year":-1347,"displayYear":"ca. 1347 f.Kr.","title":"Akhenaton grunnlegger byen Akhetaten","difficulty":2,"category":"Religion","period":"Oldtiden","region":"Egypt","emoji":"☀️","image":"","info":"Farao Akhenaton grunnla en ny by som sentrum for dyrkelsen av solguden Aton. Byen, som i dag kalles Amarna, ble forlatt som kongelig sentrum kort tid etter hans regjeringstid.","tags":["Religion","Egypt","bronsealder"],"sourceLabel":"UCLA Encyclopedia of Egyptology; Timelines of World History (2002), s. 32","sourceUrl":"https://escholarship.org/uc/item/1k66566f","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[32],"pdfPages":[36],"note":"Boka bruker ca. 1350 f.Kr. Anna Stevens (2016), Tell el-Amarna, daterer grunnleggelsen til ca. 1347 f.Kr."}],"skipYearGuess":true},
  {"id":"orakelbein-kina-ca-1300-fkr","bankId":"TWH15","year":-1300,"displayYear":"ca. 1300 f.Kr.","title":"Kinesisk skrift brukes på orakelbein","difficulty":2,"category":"Kultur","period":"Oldtiden","region":"Kina","emoji":"✍️","image":"","info":"Under Shang-dynastiet ble spørsmål og spådommer risset inn på dyrebein og skilpaddeskall. Inskripsjonene er blant de eldste bevarte eksemplene på utviklet kinesisk skrift.","tags":["Kultur","Kina","bronsealder"],"sourceLabel":"Asian Art Museum; Timelines of World History (2002), s. 32","sourceUrl":"https://searchcollection.asianart.org/objects/6787/fragment-of-oracle-bone","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[32],"pdfPages":[36],"note":"Boka daterer tidlige orakelinnskrifter til ca. 1400 f.Kr. Kontrollkildens gjenstand dateres til 1300–1050 f.Kr.; kortet beskriver dokumentert bruk omkring 1300, ikke et eksakt oppfinnelsesår."}],"skipYearGuess":true},
  {"id":"slaget-kadesh-ca-1274-fkr","bankId":"TWH16","year":-1274,"displayYear":"ca. 1274 f.Kr.","title":"Egyptere og hettitter møtes i slaget ved Kadesj","difficulty":2,"category":"Krig og konflikt","period":"Oldtiden","region":"Syria","emoji":"⚔️","image":"","info":"Ramses II ledet egyptiske styrker mot hettittene ved Kadesj i dagens Syria. Slaget inngikk i rivaliseringen om innflytelse i området; en fredsavtale mellom rikene kom senere.","tags":["Krig og konflikt","Syria","bronsealder"],"sourceLabel":"Tyrkias kulturminne- og museumsdirektorat via Google Arts & Culture; Timelines of World History (2002), s. 32","sourceUrl":"https://artsandculture.google.com/asset/kade%C5%9F-antla%C5%9Fmas%C4%B1/twHd3aD_Ds-YYA","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[32],"pdfPages":[36],"note":"Boka bruker ca. 1285 f.Kr.; museumskilden bruker 1274 f.Kr. Kortet markerer datoen som omtrentlig på grunn av oldtidens kronologi."}],"skipYearGuess":true},
  {"id":"vogner-med-hjul-ca-3500-fkr","bankId":"TWH3","year":-3500,"displayYear":"ca. 3500 f.Kr.","title":"Vogner med hjul tas i bruk","difficulty":2,"category":"Teknologi","period":"Forhistorie","region":"Europa og Vest-Asia","emoji":"🛞","image":"","info":"Hjul gjorde det mulig å frakte tunge lass på vogner. Tidlige spor etter slike kjøretøy finnes i både Europa og Vest-Asia.","tags":["Teknologi","Europa og Vest-Asia"],"sourceLabel":"University of Chicago; Timelines of World History (2002), s. 19","sourceUrl":"https://isac.uchicago.edu/sites/default/files/uploads/shared/docs/oimp36.pdf","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[19],"pdfPages":[23],"note":"Bokas entydige opphav i Mesopotamia er erstattet med en bredere geografisk formulering."}],"skipYearGuess":true},
  {"id":"uruk-storby-ca-3200-fkr","bankId":"TWH4","year":-3200,"displayYear":"ca. 3200 f.Kr.","title":"Uruk blir en storby","difficulty":2,"category":"Samfunn","period":"Forhistorie","region":"Mesopotamia","emoji":"🏘️","image":"","info":"Uruk vokste til en stor by med monumentale byggverk, templer og spesialiserte håndverkere. Byen viser hvordan jordbrukssamfunn utviklet seg til komplekse bysamfunn.","tags":["Samfunn","Mesopotamia"],"sourceLabel":"Metropolitan Museum of Art; Timelines of World History (2002), s. 19","sourceUrl":"https://www.metmuseum.org/essays/uruk-the-first-city","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[19],"pdfPages":[23],"note":"Boka bruker ca. 3500 f.Kr. for framveksten; kortet gjelder Uruk som storby ca. 3200 f.Kr. etter The Met."}],"skipYearGuess":true},
  {"id":"hieroglyfer-egypt-ca-3200-fkr","bankId":"TWH5","year":-3200,"displayYear":"ca. 3200 f.Kr.","title":"Hieroglyfer tas i bruk i Egypt","difficulty":1,"category":"Kultur","period":"Forhistorie","region":"Egypt","emoji":"𓂀","image":"","info":"Egypterne utviklet en skrift med tegn som blant annet forestilte mennesker, dyr og gjenstander. Hieroglyfer ble brukt til å skrive språk, blant annet på monumenter og i religiøse tekster.","tags":["Kultur","Egypt"],"sourceLabel":"PBS; Timelines of World History (2002), s. 19","sourceUrl":"https://www.pbs.org/empires/egypt/special/hieroglyphs/introduction.html","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[19],"pdfPages":[23],"note":"Omtrentlig datering av egyptisk skrift, ikke et eksakt oppfinnelsesår."}],"skipYearGuess":true},
  {"id":"djoser-trappepyramide-ca-2650-fkr","bankId":"TWH6","year":-2650,"displayYear":"ca. 2650 f.Kr.","title":"Djosers trappepyramide bygges","difficulty":1,"category":"Arkitektur","period":"Oldtiden","region":"Egypt","emoji":"🏜️","image":"","info":"Farao Djoser fikk reist en trappepyramide i Saqqara. Monumentet markerte et viktig steg i utviklingen av Egypts pyramider og store byggverk i stein.","tags":["Arkitektur","Egypt"],"sourceLabel":"Egypts Ministry of Tourism and Antiquities; Timelines of World History (2002), s. 19","sourceUrl":"https://egymonuments.gov.eg/monuments/the-step-pyramid-complex-of-djoser/","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[19],"pdfPages":[23],"note":"Avrundet datering innenfor Djosers regjeringstid ca. 2667–2648 f.Kr."}],"skipYearGuess":true},
  {"id":"keopspyramiden-ca-2570-fkr","bankId":"TWH7","year":-2570,"displayYear":"ca. 2570 f.Kr.","title":"Keopspyramiden bygges","difficulty":1,"category":"Arkitektur","period":"Oldtiden","region":"Egypt","emoji":"🏜️","image":"","info":"Farao Khufu, også kjent som Keops, fikk bygget den store pyramiden i Giza som gravmonument. Den er den største av pyramidene i Giza.","tags":["Arkitektur","Egypt"],"sourceLabel":"Egypts Ministry of Tourism and Antiquities; Timelines of World History (2002), s. 22","sourceUrl":"https://egymonuments.gov.eg/monuments/the-great-pyramid/","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[22],"pdfPages":[26],"note":"Boka bruker ca. 2540 f.Kr.; kortet bruker et avrundet år innenfor regjeringstiden ca. 2589–2566 oppgitt av antikvitetsmyndighetene. Ikke kjent fullføringsår."}],"skipYearGuess":true},
  {"id":"stonehenge-store-steiner-ca-2500-fkr","bankId":"TWH8","year":-2500,"displayYear":"ca. 2500 f.Kr.","title":"De store steinene ved Stonehenge reises","difficulty":1,"category":"Arkitektur","period":"Oldtiden","region":"Storbritannia","emoji":"🪨","image":"","info":"Store sarsensteiner ble reist ved Stonehenge i Sør-England. Monumentet ble utviklet i flere byggefaser og har en orientering knyttet til solas stilling ved solverv.","tags":["Arkitektur","Storbritannia"],"sourceLabel":"British Museum; Timelines of World History (2002), s. 25, 23","sourceUrl":"https://www.britishmuseum.org/exhibitions/world-stonehenge/stonehenge-timeline","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[25,23],"pdfPages":[29,27],"note":"Bokas byggeperiode ca. 2000–1500 f.Kr. er erstattet med ca. 2500 f.Kr. for de store sarsensteinene etter British Museum og English Heritage."}],"skipYearGuess":true},
  {"id":"sargon-akkadiske-riket-ca-2300-fkr","bankId":"TWH9","year":-2300,"displayYear":"ca. 2300 f.Kr.","title":"Sargon bygger det akkadiske riket","difficulty":2,"category":"Politikk","period":"Oldtiden","region":"Mesopotamia","emoji":"👑","image":"","info":"Sargon av Akkad samlet flere mesopotamiske bystater under sitt styre. Riket hans ble en tidlig stormakt som omfattet flere folk og byer.","tags":["Politikk","Mesopotamia"],"sourceLabel":"Metropolitan Museum of Art; Timelines of World History (2002), s. 26, 28","sourceUrl":"https://www.metmuseum.org/exhibitions/listings/2003/art-of-the-first-cities","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[26,28],"pdfPages":[30,32],"note":"Omtrentlig datering av erobringene, ikke eksakt tiltredelsesår."}],"skipYearGuess":true},
  {"id":"solvognen-trundholm-ca-1400-fkr","bankId":"TWH10","year":-1400,"displayYear":"ca. 1400 f.Kr.","title":"Solvognen fra Trundholm blir laget","difficulty":2,"category":"Kultur","period":"Oldtiden","region":"Danmark","emoji":"☀️","image":"","info":"En bronsehest trekker en skive med gullbelegg på den ene siden. Solvognen tolkes som en framstilling av solas reise og gir innblikk i forestillinger fra nordisk bronsealder.","tags":["Kultur","Danmark"],"sourceLabel":"Nationalmuseet; Timelines of World History (2002), s. 27","sourceUrl":"https://natmus.dk/historisk-viden/danmark/oldtid-indtil-aar-1050/bronzealderen-1700-fkr-500-fkr/solvognen/","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[27],"pdfPages":[31],"note":"Boka bruker ca. 1650 f.Kr.; kortet følger Nationalmuseets datering ca. 1400 f.Kr. Gjelder framstillingen, ikke det moderne funnet."}],"skipYearGuess":true},
  {"id":"nils-blir-fodt-1999","bankId":"SPECIAL-NILS","year":1999,"displayYear":"1999","title":"Nils blir født","difficulty":1,"category":"Personlig historie","period":"Nyere tid","region":"Norge","topics":["norsk-historie"],"emoji":"✦","image":"nils-hybrid.png","info":"Nils blir født i 1999. Et personlig bonuskort som alltid kombinerer Shiny og Corrupted: fire ganger poengene ved riktig svar, men to liv tapt ved feil i liv-modus. Portrettet er en fantasifull illustrasjon av en voksen figur.","sourceLabel":"Personlig opplysning fra Nils","tags":["bonus","hybrid"],"fixedVariant":"hybrid","specialChance":0.025},
  {"id":"hijra-622","bankId":"U1","year":622,"displayYear":"622","title":"Muhammed utvandrer fra Mekka til Medina","difficulty":2,"category":"Religion","period":"Middelalderen","region":"Den arabiske halvøy","emoji":"☪️","image":"","info":"Utvandringen kalles hijra og ble et vendepunkt for det muslimske fellesskapet. Året er utgangspunktet for den islamske tidsregningen.","tags":["Religion","Den arabiske halvøy"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/hijra","suggestionSources":["user-suggestions-2026-09-20"]},
  {"id":"landsloven-1274","bankId":"U2","year":1274,"displayYear":"1274","title":"Magnus Lagabøtes landslov innføres","difficulty":2,"category":"Politikk","period":"Middelalderen","region":"Norge","emoji":"📜","image":"","info":"Landsloven samlet store deler av lovverket for Norge i én felles lovbok. Den fikk betydning for rettsordningen i flere hundre år.","tags":["Politikk","Norge"],"sourceLabel":"Nasjonalbiblioteket","sourceUrl":"https://www.nb.no/historier-fra-samlingen/var-forste-lovbok/","suggestionSources":["user-suggestions-2026-09-20"],"topics":["norsk-historie"]},
  {"id":"newton-principia-1687","bankId":"U3","year":1687,"displayYear":"1687","title":"Newton utgir Principia","difficulty":2,"category":"Vitenskap","period":"Tidlig nytid","region":"England","emoji":"🍎","image":"","info":"Isaac Newton samlet bevegelseslovene og loven om universell gravitasjon i verket Principia. Boka ble grunnleggende for klassisk mekanikk.","tags":["Vitenskap","England"],"sourceLabel":"Cambridge University Library","sourceUrl":"https://wwwe.lib.cam.ac.uk/CUL/exhibitions/Footprints_of_the_Lion/gravity_glory.html","suggestionSources":["user-suggestions-2026-09-20"]},
  {"id":"darwin-artenes-opprinnelse-1859","bankId":"U4","year":1859,"displayYear":"1859","title":"Darwin utgir Artenes opprinnelse","difficulty":1,"category":"Vitenskap","period":"1800-tallet","region":"Storbritannia","emoji":"🐢","image":"","info":"Charles Darwin presenterte hvordan naturlig utvalg kan bidra til at arter endrer seg over tid. Boka fikk stor betydning for biologien.","tags":["Vitenskap","Storbritannia"],"sourceLabel":"University of Cambridge","sourceUrl":"https://www.cam.ac.uk/news/darwins-delay-the-stuff-of-myth","suggestionSources":["user-suggestions-2026-09-20"]},
  {"id":"kvinner-begrenset-kommunal-stemmerett-1901","bankId":"U5","year":1901,"displayYear":"1901","title":"Kvinner får begrenset stemmerett ved kommunevalg","difficulty":2,"category":"Politikk","period":"1900-tallet","region":"Norge","emoji":"🗳️","image":"","info":"Kvinner som oppfylte bestemte økonomiske vilkår, fikk stemmerett ved kommunevalg. Dette var et steg mot allmenn stemmerett, men omfattet ennå ikke alle kvinner.","tags":["Politikk","Norge"],"sourceLabel":"Stortinget","sourceUrl":"https://stortinget.no/no/Stortinget-og-demokratiet/stemmerettsjubileet-2019/fattigdom-stemmerett/tidslinje/","suggestionSources":["user-suggestions-2026-09-20"],"topics":["norsk-historie"]},
  {"id":"amundsen-sydpolen-1911","bankId":"U6","year":1911,"displayYear":"1911","title":"Amundsens ekspedisjon når Sydpolen","difficulty":1,"category":"Utforskning","period":"1900-tallet","region":"Antarktis","emoji":"🧭","image":"","info":"Roald Amundsen og fire ledsagere nådde Sydpolen 14. desember. De var den første dokumenterte ekspedisjonen som kom fram til polpunktet.","tags":["Utforskning","Antarktis"],"sourceLabel":"Frammuseet","sourceUrl":"https://frammuseum.no/en/polar-history/expeditions/the-third-fram-expedition-1910-1914/","suggestionSources":["user-suggestions-2026-09-20"],"topics":["norsk-historie"]},
  {"id":"menneskerettighetserklaeringen-1948","bankId":"U7","year":1948,"displayYear":"1948","title":"FNs verdenserklæring om menneskerettigheter vedtas","difficulty":1,"category":"Internasjonal politikk","period":"Etterkrigstiden","region":"Verden","emoji":"🕊️","image":"","info":"FNs generalforsamling vedtok erklæringen 10. desember. Den formulerer grunnleggende rettigheter som skal gjelde for alle mennesker.","tags":["Internasjonal politikk","Verden"],"sourceLabel":"FN-sambandet","sourceUrl":"https://fn.no/avtaler/menneskerettigheter/fns-verdenserklaering-om-menneskerettigheter","suggestionSources":["user-suggestions-2026-09-20"]},
  {"id":"vinter-ol-oslo-1952","bankId":"U8","year":1952,"displayYear":"1952","title":"Oslo arrangerer vinter-OL","difficulty":1,"category":"Idrett","period":"Etterkrigstiden","region":"Norge","emoji":"⛷️","image":"","info":"Norge arrangerte olympiske leker for første gang. Vinterlekene samlet utøvere fra mange land til konkurranser i Oslo og nærliggende områder.","tags":["Idrett","Norge"],"sourceLabel":"Norges Olympiske Museum","sourceUrl":"https://ol.museum.no/om-olympiske-leker/ol-historie2","suggestionSources":["user-suggestions-2026-09-20"],"topics":["norsk-historie"]},
  {"id":"fjernsyn-offisiell-apning-1960","bankId":"U9","year":1960,"displayYear":"1960","title":"Fjernsynet åpner offisielt i Norge","difficulty":2,"category":"Kultur","period":"Etterkrigstiden","region":"Norge","emoji":"📺","image":"","info":"Etter flere år med prøvesendinger ble det norske fjernsynet offisielt åpnet 20. august. TV ble etter hvert en viktig del av hverdagen.","tags":["Kultur","Norge"],"sourceLabel":"NRK","sourceUrl":"https://arkiv.nrk.no/programoversikt/avansert/index19d5.html","suggestionSources":["user-suggestions-2026-09-20"],"topics":["norsk-historie"]},
  {"id":"ekofisk-funnet-1969","bankId":"U10","year":1969,"displayYear":"1969","title":"Ekofiskfeltet blir oppdaget","difficulty":1,"category":"Økonomi","period":"Etterkrigstiden","region":"Norge","emoji":"🛢️","image":"","info":"Funnet av det store oljefeltet Ekofisk ble et vendepunkt for norsk petroleumsvirksomhet. Det la grunnlaget for en næring som fikk stor betydning for økonomien.","tags":["Økonomi","Norge"],"sourceLabel":"Norsk petroleum","sourceUrl":"https://www.norskpetroleum.no/fakta/funn/24-2-ekofisk/","suggestionSources":["user-suggestions-2026-09-20"],"topics":["norsk-historie"]},
  {"id":"gro-forste-kvinnelige-statsminister-1981","bankId":"U11","year":1981,"displayYear":"1981","title":"Gro Harlem Brundtland blir Norges første kvinnelige statsminister","difficulty":1,"category":"Politikk","period":"Etterkrigstiden","region":"Norge","emoji":"🏛️","image":"","info":"Gro Harlem Brundtland overtok som statsminister 4. februar. Hun var den første kvinnen som ledet en norsk regjering.","tags":["Politikk","Norge"],"sourceLabel":"Regjeringen","sourceUrl":"https://www.regjeringen.no/en/the-government/previous-governments/historiske-artikler/offices/prime-minister-since-1814/gro-harlem-brundtland/id463420/","suggestionSources":["user-suggestions-2026-09-20"],"topics":["norsk-historie"]},
  {"id":"sovjetunionen-opploses-1991","bankId":"U12","year":1991,"displayYear":"1991","title":"Sovjetunionen oppløses","difficulty":1,"category":"Internasjonal politikk","period":"Den kalde krigen","region":"Europa og Asia","emoji":"🌍","image":"","info":"Sovjetunionen ble formelt oppløst i desember. De tidligere sovjetrepublikkene ble selvstendige stater, og det politiske kartet ble endret.","tags":["Internasjonal politikk","Europa og Asia"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/Sovjetunionen","suggestionSources":["user-suggestions-2026-09-20"]},
  {"id":"norge-nei-eu-1994","bankId":"U13","year":1994,"displayYear":"1994","title":"Norge sier nei til EU-medlemskap","difficulty":1,"category":"Politikk","period":"Nyere tid","region":"Norge","emoji":"🗳️","image":"","info":"Ved folkeavstemningen 28. november stemte et flertall mot norsk medlemskap i EU. Norge ble dermed stående utenfor unionen.","tags":["Politikk","Norge"],"sourceLabel":"Stortinget","sourceUrl":"https://www.stortinget.no/no/Stortinget-og-demokratiet/Storting-og-regjering/Folkestyret/Folkeavstemninger/","suggestionSources":["user-suggestions-2026-09-20"],"topics":["norsk-historie"]},
  {"id":"vinter-ol-lillehammer-1994","bankId":"U14","year":1994,"displayYear":"1994","title":"Lillehammer arrangerer vinter-OL","difficulty":1,"category":"Idrett","period":"Nyere tid","region":"Norge","emoji":"🎿","image":"","info":"De olympiske vinterlekene ble arrangert på Lillehammer og andre steder i regionen. Det var andre gang Norge var vertskap for OL.","tags":["Idrett","Norge"],"sourceLabel":"Norges Olympiske Museum","sourceUrl":"https://ol.museum.no/om-olympiske-leker/vinterleker/lillehammer-1994","suggestionSources":["user-suggestions-2026-09-20"],"topics":["norsk-historie"]},
  {"id":"catalhoyuk-bosetting-ca-7400-fkr","bankId":"TWH1","year":-7400,"displayYear":"ca. 7400 f.Kr.","title":"Bosettingen Çatalhöyük vokser fram","difficulty":3,"category":"Samfunn","period":"Forhistorie","region":"Anatolia","emoji":"🏘️","image":"","info":"I Anatolia, i dagens Tyrkia, vokste en stor jordbruksbosetting fram. Husene lå tett sammen, og funn fra stedet gir innblikk i livet i yngre steinalder.","tags":["Çatalhöyük","bosetting","jordbruk"],"sourceLabel":"UNESCO; Timelines of World History (2002), s. 14","sourceUrl":"https://whc.unesco.org/en/list/1405/","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[14],"pdfPages":[18],"note":"Boka oppgir ca. 7000 f.Kr. Årstallet ca. 7400 f.Kr. følger UNESCOs datering av den tidligste bosettingen."}],"skipYearGuess":true},
  {"id":"bandkeramisk-kultur-ca-5500-fkr","bankId":"TWH2","year":-5500,"displayYear":"ca. 5500 f.Kr.","title":"Den båndkeramiske kulturen vokser fram","difficulty":3,"category":"Kultur","period":"Forhistorie","region":"Sentral-Europa","emoji":"🏺","image":"","info":"Jordbrukssamfunn i Sentral-Europa laget keramikk med innrissede båndmønstre. Kulturen forbindes også med langhus, korndyrking og husdyrhold.","tags":["båndkeramikk","jordbruk","steinalder"],"sourceLabel":"Timelines of World History (2002), s. 15; Scientific Reports (2016)","sourceUrl":"https://www.nature.com/articles/srep29458","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[15],"pdfPages":[19],"note":"Bokas omtrentlige datering er kontrollert mot forskningsartikkelen."}],"skipYearGuess":true},
  {"id":"jordbrukssamfunn-ca-10000-fkr","year":-10000,"displayYear":"ca. 10 000 f.Kr.","title":"Jordbrukssamfunn vokser fram","category":"Samfunn","period":"Forhistorie","region":"Verden","emoji":"🌾","image":"","info":"Mennesker begynte gradvis å dyrke jorda og holde husdyr. Det førte til mer faste bosettinger, større samfunn og store endringer i hvordan mennesker levde.","tags":["jordbruk","bosetting","neolitikum"],"bankId":"G1","difficulty":1,"bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[14],"pdfPages":[18],"note":"Tematisk støtte for jordbrukets framvekst. Boka daterer dyrking i Nord-Syria til ca. 9000 f.Kr.; dette kortet beskriver den bredere prosessen."}]},
  {"id":"skrift-mesopotamia-ca-3000-fkr","year":-3000,"displayYear":"ca. 3000 f.Kr.","title":"Skrift tas i bruk i Mesopotamia","category":"Kultur","period":"Oldtiden","region":"Mesopotamia","emoji":"✍️","image":"","info":"Tidlige skriftsystemer gjorde det mulig å registrere handel, avtaler, lover og historie. Skrift ble et viktig verktøy for større og mer organiserte samfunn.","tags":["skrift","mesopotamia","kileskrift"],"bankId":"G2","difficulty":1,"bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[19],"pdfPages":[23],"note":"Tematisk støtte for tidlig skrift. Boka beskriver utviklingen i slutten av det fjerde årtusen f.Kr.; eksisterende kort beholder sin brede datering ca. 3000 f.Kr."}]},
  {"id":"vestromerriket-faller-476","year":476,"displayYear":"476","title":"Vestromerriket faller","category":"Politikk","period":"Antikken","region":"Europa","emoji":"🏛️","image":"","info":"Den siste vestromerske keiseren ble avsatt. Året 476 brukes ofte som et symbolsk skille mellom antikken og middelalderen i Vest-Europa.","tags":["romerriket","antikken","middelalderen"],"bankId":"G3","difficulty":1},
  {"id":"lindisfarne-793","year":793,"displayYear":"793","title":"Vikingangrepet på Lindisfarne","category":"Krig og konflikt","period":"Vikingtid","region":"Europa","emoji":"⛵","image":"","info":"Vikinger angrep klosteret Lindisfarne på nordøstkysten av England. Angrepet brukes ofte som en markering på starten av vikingtiden.","tags":["vikinger","lindisfarne","vikingtid"],"bankId":"G4","difficulty":1,"topics":["norsk-historie"]},
  {"id":"hafrsfjord-tradisjonelt-872","year":872,"displayYear":"trad. 872","title":"Slaget i Hafrsfjord","category":"Politikk","period":"Vikingtid","region":"Norge","emoji":"⚔️","image":"","info":"872 er det tradisjonelle årstallet for slaget i Hafrsfjord og rikssamlingen under Harald Hårfagre. Historikere mener slaget trolig fant sted senere, muligens i 880-årene.","tags":["hafrsfjord","harald hårfagre","rikssamling"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G5","difficulty":1,"topics":["norsk-historie"]},
  {"id":"olav-tryggvason-kristning-995","year":995,"displayYear":"995","title":"Olav Tryggvason blir konge og fremmer kristningen","category":"Religion","period":"Vikingtid","region":"Norge","emoji":"⛪","image":"","info":"Olav Tryggvason ble konge og arbeidet aktivt for å spre kristendommen i Norge. Perioden ble viktig i overgangen fra norrøn religion til kristendom.","tags":["olav tryggvason","kristning","vikingtid"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G6","difficulty":2,"topics":["norsk-historie"]},
  {"id":"stiklestad-1030","year":1030,"displayYear":"1030","title":"Slaget på Stiklestad","category":"Krig og konflikt","period":"Vikingtid","region":"Norge","emoji":"⚔️","image":"","info":"Olav Haraldsson ble drept i slaget på Stiklestad. Han ble senere helgenkåret, og minnet om ham fikk stor betydning for kristendommen og kongemakten i Norge.","tags":["stiklestad","olav den hellige","kristning"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G7","difficulty":1,"topics":["norsk-historie"]},
  {"id":"erkebispesete-nidaros-1152-1153","year":1152,"acceptedYears":[1152,1153],"displayYear":"1152/1153","title":"Erkebispesetet i Nidaros opprettes","category":"Religion","period":"Middelalderen","region":"Norge","emoji":"⛪","image":"","info":"Nidaros fikk sitt eget erkebispesete og ble sentrum for den norske kirkeprovinsen. Nidarosdomen utviklet seg videre som et viktig religiøst sentrum.","tags":["nidaros","erkebispesete","kirke"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G8","difficulty":3,"topics":["norsk-historie"]},
  {"id":"magnus-erlingsson-krones-1163","year":1163,"displayYear":"1163","title":"Magnus Erlingsson krones til konge","category":"Politikk","period":"Middelalderen","region":"Norge","emoji":"👑","image":"","info":"Magnus Erlingsson ble kronet med støtte fra kirken. Samtidig ble det innført nye regler for tronfølgen, noe som styrket kirkens innflytelse over kongemakten.","tags":["magnus erlingsson","kroning","tronfølge"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G9","difficulty":3,"topics":["norsk-historie"]},
  {"id":"sverre-birkebeinerne-1177","year":1177,"displayYear":"1177","title":"Sverre blir konge for birkebeinerne","category":"Politikk","period":"Middelalderen","region":"Norge","emoji":"👑","image":"","info":"Sverre ble utropt til konge av birkebeinerne. Etter flere militære seire ble han enekonge og arbeidet for å styrke kongemakten og redusere kirkens politiske makt.","tags":["sverre","birkebeinerne","borgerkrigstiden"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G10","difficulty":3,"topics":["norsk-historie"]},
  {"id":"magna-carta-1215","year":1215,"displayYear":"1215","title":"Magna Carta undertegnes","category":"Politikk","period":"Middelalderen","region":"England","emoji":"📜","image":"","info":"Den engelske kongen måtte godta et dokument som satte enkelte grenser for kongemakten. Magna Carta fikk senere stor symbolsk betydning i utviklingen av rettigheter og begrenset statsmakt.","tags":["magna carta","rettigheter","kongemakt"],"bankId":"G11","difficulty":2},
  {"id":"norgesveldet-storst-1263","year":1263,"displayYear":"1263","title":"Norgesveldet når sin største utstrekning","category":"Politikk","period":"Middelalderen","region":"Norge","emoji":"🗺️","image":"","info":"Ved Håkon Håkonssons død omfattet den norske kongemakten områder både øst og vest for dagens Norge, blant annet Island, Orknøyene og deler av dagens Sverige.","tags":["norgesveldet","håkon håkonsson","middelalderen"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G12","difficulty":3,"topics":["norsk-historie"]},
  {"id":"kongeslekt-mannssiden-1319","year":1319,"displayYear":"1319","title":"Den norske kongeslekten dør ut på mannssiden","category":"Politikk","period":"Middelalderen","region":"Norge","emoji":"👑","image":"","info":"Da Håkon 5. Magnusson døde uten en mannlig arving, kom Norge inn i en lang periode med unionskongedømmer med andre nordiske riker.","tags":["håkon 5","union","kongeslekt"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G13","difficulty":3,"topics":["norsk-historie"]},
  {"id":"svartedauden-norge-1349-1350","year":1349,"acceptedYears":[1349,1350],"displayYear":"1349/1350","title":"Svartedauden rammer Norge","category":"Samfunn","period":"Middelalderen","region":"Norge","emoji":"⚫","image":"","info":"Pestepidemien førte til en dramatisk nedgang i folketallet og fikk store følger for gårdsdrift, økonomi, kirke og samfunn. Befolkningen brukte lang tid på å hente seg inn igjen.","tags":["svartedauden","pest","befolkning"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G14","difficulty":1,"topics":["norsk-historie"]},
  {"id":"kalmarunionen-1397","year":1397,"displayYear":"1397","title":"Kalmarunionen opprettes","category":"Politikk","period":"Middelalderen","region":"Norden","emoji":"🤝","image":"","info":"Danmark, Norge og Sverige ble samlet under en felles monark. Unionen var preget av skiftende maktforhold og konflikter, særlig mellom Danmark og Sverige.","tags":["kalmarunionen","norden","margrete"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G15","difficulty":2,"topics":["norsk-historie"]},
  {"id":"boktrykkerkunsten-ca-1450","year":1450,"displayYear":"ca. 1450","title":"Boktrykkerkunsten slår gjennom i Europa","category":"Teknologi","period":"Tidlig nytid","region":"Europa","emoji":"🖨️","image":"","info":"Trykketeknikk med løse typer gjorde bøker raskere og billigere å produsere. Det bidro til at kunnskap og ideer kunne spres til langt flere mennesker.","tags":["gutenberg","boktrykk","teknologi"],"bankId":"G16","difficulty":1},
  {"id":"reformasjonen-danmark-norge-1536","year":1536,"displayYear":"1536","title":"Reformasjonen innføres i Danmark-Norge","category":"Religion","period":"Tidlig nytid","region":"Danmark-Norge","emoji":"⛪","image":"","info":"Christian 3 gjennomførte reformasjonen og gjorde den lutherske kirken til statens kirke. Kongemakten overtok mye av kirkens eiendom og Norge mistet samtidig sin status som eget kongerike.","tags":["reformasjonen","christian 3","danmark-norge"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G17","difficulty":2,"topics":["norsk-historie"]},
  {"id":"bromsebro-1645","year":1645,"displayYear":"1645","title":"Danmark-Norge avstår Jämtland og Herjedalen","category":"Krig og konflikt","period":"Tidlig nytid","region":"Norden","emoji":"🗺️","image":"","info":"Etter krig med Sverige måtte Danmark-Norge ved freden i Brömsebro avstå blant annet Jämtland og Herjedalen til Sverige.","tags":["brömsebro","jämtland","herjedalen"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G18","difficulty":3,"topics":["norsk-historie"]},
  {"id":"roskilde-1658","year":1658,"displayYear":"1658","title":"Norge mister Båhuslen og Trondhjems len","category":"Krig og konflikt","period":"Tidlig nytid","region":"Norden","emoji":"🗺️","image":"","info":"Ved freden i Roskilde måtte Danmark-Norge avstå flere områder til Sverige. For Norge gjaldt dette blant annet Båhuslen og Trondhjems len.","tags":["roskilde","båhuslen","trondhjems len"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G19","difficulty":3,"topics":["norsk-historie"]},
  {"id":"eneveldet-1660","year":1660,"displayYear":"1660","title":"Eneveldet innføres i Danmark-Norge","category":"Politikk","period":"Tidlig nytid","region":"Danmark-Norge","emoji":"👑","image":"","info":"Kong Frederik 3 innførte enevelde, der kongen fikk svært omfattende politisk makt. Styreformen besto i Danmark-Norge fram til 1814.","tags":["enevelde","frederik 3","kongemakt"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G20","difficulty":3,"topics":["norsk-historie"]},
  {"id":"franske-revolusjon-1789","year":1789,"displayYear":"1789","title":"Den franske revolusjonen begynner","category":"Politikk","period":"Nyere tid","region":"Frankrike","emoji":"🇫🇷","image":"","info":"Revolusjonen utfordret kongemakten og standssamfunnet i Frankrike. Ideer om frihet, likhet, folkestyre og rettigheter fikk stor betydning også utenfor Frankrike.","tags":["revolusjon","frankrike","demokrati"],"bankId":"G21","difficulty":1},
  {"id":"norges-grunnlov-1814","year":1814,"displayYear":"1814","title":"Norge får Grunnloven","category":"Politikk","period":"Nyere tid","region":"Norge","emoji":"📕","image":"","info":"Riksforsamlingen på Eidsvoll vedtok Grunnloven 17. mai. Norge fikk egne nasjonale institusjoner og gikk senere samme år inn i union med Sverige.","tags":["grunnloven","eidsvoll","1814"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G22","difficulty":1,"topics":["norsk-historie"]},
  {"id":"norges-bank-1816","year":1816,"displayYear":"1816","title":"Norges Bank opprettes","category":"Økonomi","period":"1800-tallet","region":"Norge","emoji":"🏦","image":"","info":"Den norske sentralbanken ble opprettet kort tid etter 1814. Banken fikk en sentral rolle i arbeidet med et eget norsk pengevesen og økonomisk stabilitet.","tags":["norges bank","økonomi","sentralbank"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G23","difficulty":3,"topics":["norsk-historie"]},
  {"id":"formannskapslovene-1837","year":1837,"displayYear":"1837","title":"Kommunalt selvstyre innføres","category":"Politikk","period":"1800-tallet","region":"Norge","emoji":"🏘️","image":"","info":"Formannskapslovene opprettet folkevalgte kommunale organer. Lokalsamfunn fikk dermed større ansvar for egne saker og Norge fikk et mer desentralisert styresett.","tags":["formannskapslovene","kommune","lokaldemokrati"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G24","difficulty":3,"topics":["norsk-historie"]},
  {"id":"espressomaskinen-1884","year":1884,"displayYear":"1884","title":"Espressomaskinen finnes opp","category":"Teknologi","period":"Industrialisering","region":"Italia","emoji":"☕","image":"","info":"Angelo Moriondo fikk patent på en tidlig maskin som brukte damp og varmt vann til å lage kaffe raskere. Den regnes som en viktig forløper til moderne espressomaskiner.","tags":["espresso","oppfinnelse","teknologi"],"bankId":"G25","difficulty":3},
  {"id":"parlamentarismen-1884","year":1884,"displayYear":"1884","title":"Parlamentarismen innføres i Norge","category":"Politikk","period":"1800-tallet","region":"Norge","emoji":"🏛️","image":"","info":"Etter riksrettssaken mot regjeringen Selmer ble det etablert at en regjering måtte ha støtte i Stortinget. Dette styrket Stortingets stilling i det norske politiske systemet.","tags":["parlamentarisme","stortinget","riksrett"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G26","difficulty":2,"topics":["norsk-historie"]},
  {"id":"unionsopplosningen-1905","year":1905,"displayYear":"1905","title":"Unionen med Sverige oppløses","category":"Politikk","period":"1900-tallet","region":"Norge","emoji":"🇳🇴","image":"","info":"Stortinget vedtok 7. juni at unionen med Sverige var oppløst. Etter forhandlinger og folkeavstemninger ble Norge et selvstendig konstitusjonelt monarki med Haakon 7 som konge.","tags":["1905","union","sverige"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G27","difficulty":1,"topics":["norsk-historie"]},
  {"id":"kvinner-stemmerett-1913","year":1913,"displayYear":"1913","title":"Kvinner får alminnelig stemmerett","category":"Politikk","period":"1900-tallet","region":"Norge","emoji":"🗳️","image":"","info":"Stortinget vedtok alminnelig stemmerett for kvinner på samme vilkår som for menn. Norge var blant de tidlige landene som innførte full stemmerett for kvinner.","tags":["stemmerett","kvinner","demokrati"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G28","difficulty":1,"topics":["norsk-historie"]},
  {"id":"forste-verdenskrig-1914","year":1914,"displayYear":"1914","title":"Første verdenskrig begynner","category":"Krig og konflikt","period":"1900-tallet","region":"Verden","emoji":"🪖","image":"","info":"Etter attentatet på erkehertug Franz Ferdinand utviklet konflikten seg raskt gjennom Europas allianser. Krigen varte til 1918 og førte til enorme tap og store politiske endringer.","tags":["første verdenskrig","1914","krig"],"bankId":"G29","difficulty":1},
  {"id":"arbeiderpartiet-regjering-1928","year":1928,"displayYear":"1928","title":"Arbeiderpartiet danner sin første regjering","category":"Politikk","period":"Mellomkrigstiden","region":"Norge","emoji":"🏛️","image":"","info":"Arbeiderpartiet dannet regjering for første gang etter å ha blitt det største partiet ved valget i 1927. Regjeringen satt bare noen uker, men markerte et viktig skifte i norsk politisk historie.","tags":["arbeiderpartiet","regjering","mellomkrigstiden"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G30","difficulty":3,"topics":["norsk-historie"]},
  {"id":"tyskland-angriper-norge-1940","year":1940,"displayYear":"1940","title":"Tyskland angriper og okkuperer Norge","category":"Krig og konflikt","period":"Andre verdenskrig","region":"Norge","emoji":"⚔️","image":"","info":"Tyskland angrep Norge 9. april 1940. Etter felttoget fortsatte kongen og regjeringen virksomheten fra London, mens Norge var okkupert fram til frigjøringen i mai 1945.","tags":["andre verdenskrig","okkupasjon","9. april"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G31","difficulty":1,"topics":["norsk-historie"]},
  {"id":"andre-verdenskrig-slutter-1945","year":1945,"displayYear":"1945","title":"Andre verdenskrig tar slutt","category":"Krig og konflikt","period":"1900-tallet","region":"Verden","emoji":"🕊️","image":"","info":"Krigen i Europa tok slutt i mai 1945, og Japan kapitulerte senere samme år. Krigens slutt innledet en ny internasjonal orden og en omfattende gjenoppbygging.","tags":["andre verdenskrig","1945","krig"],"bankId":"G32","difficulty":1},
  {"id":"norge-nato-1949","year":1949,"displayYear":"1949","title":"Norge blir medlem av NATO","category":"Internasjonal politikk","period":"Den kalde krigen","region":"Norge","emoji":"🛡️","image":"","info":"Norge var med på å opprette NATO i 1949. Medlemskapet knyttet norsk sikkerhets- og forsvarspolitikk tett til den vestlige alliansen under den kalde krigen.","tags":["nato","den kalde krigen","forsvar"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G33","difficulty":1,"topics":["norsk-historie"]},
  {"id":"manelandingen-1969","year":1969,"displayYear":"1969","title":"Mennesket lander på månen","category":"Vitenskap og teknologi","period":"1900-tallet","region":"Verden","emoji":"🌕","image":"","info":"Apollo 11 landet på månen, og Neil Armstrong og Buzz Aldrin gikk på månens overflate. Månelandingen var et høydepunkt i romkappløpet.","tags":["apollo 11","månen","romkappløpet"],"bankId":"G34","difficulty":1},
  {"id":"ef-folkeavstemning-1972","year":1972,"displayYear":"1972","title":"Norge sier nei til EF","category":"Politikk","period":"Etterkrigstiden","region":"Norge","emoji":"🗳️","image":"","info":"I folkeavstemningen i 1972 stemte et flertall mot norsk medlemskap i EF, forløperen til EU. Spørsmålet om europeisk medlemskap kom opp igjen i en ny folkeavstemning i 1994.","tags":["ef","folkeavstemning","eu"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G35","difficulty":2,"topics":["norsk-historie"]},
  {"id":"berlinmuren-faller-1989","year":1989,"displayYear":"1989","title":"Berlinmuren faller","category":"Politikk","period":"1900-tallet","region":"Tyskland","emoji":"🧱","image":"","info":"Grenseovergangene i Berlin ble åpnet etter store politiske endringer i Øst-Europa. Murens fall ble et symbol på slutten av den kalde krigen og veien mot tysk gjenforening.","tags":["berlinmuren","den kalde krigen","tyskland"],"bankId":"G36","difficulty":1},
  {"id":"world-wide-web-1991","year":1991,"displayYear":"1991","title":"World Wide Web blir offentlig tilgjengelig","category":"Teknologi","period":"1900-tallet","region":"Verden","emoji":"🌐","image":"","info":"World Wide Web gjorde det mulig å knytte sammen dokumenter gjennom lenker og nettlesere. Teknologien ble grunnlaget for nettet slik de fleste bruker det i dag.","tags":["internett","web","tim berners-lee"],"bankId":"G37","difficulty":1},
  {"id":"terrorangrepene-22-juli-2011","year":2011,"displayYear":"2011","title":"Terrorangrepene 22. juli","category":"Krig og konflikt","period":"2000-tallet","region":"Norge","emoji":"🕯️","image":"","info":"22. juli 2011 ble Regjeringskvartalet i Oslo rammet av en bombe, etterfulgt av et massedrap på Utøya. 77 mennesker ble drept i terrorangrepene.","tags":["22. juli","utøya","terror"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/25_viktige_%C3%A5rstall_i_norsk_historie","bankId":"G38","difficulty":1,"topics":["norsk-historie"]},

  {"id":"jeriko-grunnlegges-for-7000-fkr","bankId":"N1","year":-7000,"displayYear":"før 7000 f.Kr.","title":"Jeriko, en av verdens eldste byer, grunnlegges","difficulty":3,"category":"Samfunn","period":"Forhistorie","region":"Midtøsten","emoji":"🏘️","image":"","info":"Jeriko utviklet seg svært tidlig til en fast bosetting med omfattende byggverk. Byen brukes ofte som et eksempel på overgangen til mer bofaste samfunn i den tidlige jordbrukstiden.","tags":["Jeriko","byer","bosetting"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"egypt-samles-ca-3100-fkr","bankId":"N2","year":-3100,"displayYear":"ca. 3100 f.Kr.","title":"Egypt samles til ett rike","difficulty":3,"category":"Politikk","period":"Oldtiden","region":"Egypt","emoji":"👑","image":"","info":"Øvre og Nedre Egypt ble samlet under én kongemakt. Samlingen la grunnlaget for den egyptiske staten som utviklet seg langs Nilen.","tags":["Egypt","rikssamling","farao"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","bookSources":[{"bookId":"teeple-timelines-world-history-2002","pages":[19],"pdfPages":[23],"note":"Samlingen av Øvre og Nedre Egypt omkring 3100 f.Kr. omtales også i boka."}]},
  {"id":"induskulturen-oppstar-ca-2500-fkr","bankId":"N3","year":-2500,"displayYear":"ca. 2500–2300 f.Kr.","title":"Induskulturen oppstår","difficulty":3,"category":"Samfunn","period":"Oldtiden","region":"Sør-Asia","emoji":"🏙️","image":"","info":"Induskulturen vokste fram i Indusdalen med store, planlagte byer som Harappa og Mohenjo-daro. Kulturen var en av oldtidens store bysivilisasjoner.","tags":["Induskulturen","Indusdalen","bysivilisasjon"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":-2500,"end":-2300}},
  {"id":"hammurabi-babylonia-ca-1700-fkr","bankId":"N4","year":-1700,"displayYear":"ca. 1700 f.Kr.","title":"Hammurabi samler Babylonia","difficulty":3,"category":"Politikk","period":"Oldtiden","region":"Mesopotamia","emoji":"⚖️","image":"","info":"Hammurabi styrket Babylon og samlet store deler av Mesopotamia under sitt styre. Han er også kjent for en omfattende lovsamling som er bevart fra perioden.","tags":["Hammurabi","Babylonia","lover"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"roma-grunnlegges-trad-753-fkr","bankId":"N5","year":-753,"displayYear":"trad. 753 f.Kr.","title":"Roma grunnlegges","difficulty":3,"category":"Samfunn","period":"Antikken","region":"Italia","emoji":"🐺","image":"","info":"Ifølge romersk tradisjon ble Roma grunnlagt i 753 f.Kr. Byen vokste senere til sentrum for en republikk og deretter et stort imperium.","tags":["Roma","Romerriket","Italia"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"demokrati-athen-500-400-fkr","bankId":"N6","year":-500,"displayYear":"500–400-tallet f.Kr.","title":"Demokratiet vokser fram i Athen","difficulty":2,"category":"Politikk","period":"Antikken","region":"Hellas","emoji":"🏛️","image":"","info":"I Athen utviklet det seg et system der mannlige borgere kunne delta direkte i politiske beslutninger. Det athenske demokratiet ble viktig for senere ideer om folkestyre.","tags":["Athen","demokrati","Hellas"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":-500,"end":-400}},
  {"id":"perserkrigene-490-449-fkr","bankId":"N7","year":-490,"displayYear":"490–449 f.Kr.","title":"Perserkrigene","difficulty":3,"category":"Krig og konflikt","period":"Antikken","region":"Hellas og Perserriket","emoji":"⚔️","image":"","info":"Perserriket forsøkte flere ganger å underlegge seg de greske bystatene. De greske statene slo tilbake invasjonene, og Athen fikk en sterkere stilling i regionen.","tags":["Perserkrigene","Persia","Hellas"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":-490,"end":-449}},
  {"id":"aleksander-den-store-334-323-fkr","bankId":"N8","year":-334,"displayYear":"334–323 f.Kr.","title":"Aleksander den store erobrer et enormt rike","difficulty":2,"category":"Krig og konflikt","period":"Antikken","region":"Middelhavet og Asia","emoji":"🗺️","image":"","info":"Aleksander av Makedonia erobret Perserriket, Egypt og områder helt til India. Erobringene spredte gresk språk og kultur over store deler av den gamle verden.","tags":["Aleksander den store","Makedonia","hellenisme"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":-334,"end":-323}},
  {"id":"puniske-kriger-264-146-fkr","bankId":"N9","year":-264,"displayYear":"264–146 f.Kr.","title":"De puniske krigene mellom Roma og Karthago","difficulty":3,"category":"Krig og konflikt","period":"Antikken","region":"Middelhavet","emoji":"🐘","image":"","info":"Roma og Karthago kjempet tre store kriger om makten i det vestlige Middelhavet. Roma vant til slutt og ødela Karthago i 146 f.Kr.","tags":["puniske kriger","Roma","Karthago"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":-264,"end":-146}},
  {"id":"kinesiske-mur-shi-huangdi-214-fkr","bankId":"N10","year":-214,"displayYear":"214 f.Kr.","title":"Arbeidet med Den kinesiske mur fullføres under Shi Huangdi","difficulty":3,"category":"Politikk","period":"Antikken","region":"Kina","emoji":"🧱","image":"","info":"Under den første keiseren Shi Huangdi ble eldre forsvarsverk knyttet sammen og utbygd. Disse anleggene var forløpere til senere deler av Den kinesiske mur.","tags":["Den kinesiske mur","Shi Huangdi","Kina"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"silkeveien-100-tallet-fkr","bankId":"N11","year":-150,"displayYear":"100-tallet f.Kr.","title":"Silkeveien knytter Kina og Vesten sammen","difficulty":3,"category":"Økonomi","period":"Antikken","region":"Asia og Europa","emoji":"🐫","image":"","info":"Handelsruter gjennom Sentral-Asia bandt Kina sammen med områder lenger vest. Varer, ideer, religioner og teknologi kunne dermed bevege seg over svært lange avstander.","tags":["Silkeveien","handel","Kina"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":-199,"end":-100}},
  {"id":"kristendommen-spres-ca-30","bankId":"N12","year":30,"displayYear":"ca. 30","title":"Kristendommen begynner å spre seg i Romerriket","difficulty":1,"category":"Religion","period":"Antikken","region":"Romerriket","emoji":"✝️","image":"","info":"Etter Jesu død spredte de første kristne budskapet til byer rundt Middelhavet. Paulus og andre misjonærer bidro til at den nye religionen fikk tilhengere langt utenfor Judea.","tags":["kristendom","Paulus","Romerriket"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"romerriket-storst-117","bankId":"N13","year":117,"displayYear":"117","title":"Romerriket når sin største utstrekning","difficulty":2,"category":"Politikk","period":"Antikken","region":"Europa, Nord-Afrika og Asia","emoji":"🏛️","image":"","info":"Under keiser Trajan nådde Romerriket sin største geografiske utstrekning. Riket omfattet da store deler av Europa og områder i Nord-Afrika og Vest-Asia.","tags":["Romerriket","Trajan","imperium"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"romerriket-deles-395","bankId":"N14","year":395,"displayYear":"395","title":"Romerriket deles i et vestlig og et østlig rike","difficulty":3,"category":"Politikk","period":"Antikken","region":"Europa og Middelhavet","emoji":"↔️","image":"","info":"Etter keiser Theodosius 1.s død ble riket permanent delt mellom en vestlig og en østlig del. Det østlige riket levde videre i omkring tusen år.","tags":["Romerriket","Østromerriket","Vestromerriket"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"frankerriket-chlodvig-486","bankId":"N15","year":486,"displayYear":"486","title":"Frankerriket grunnlegges under Chlodvig","difficulty":3,"category":"Politikk","period":"Tidlig middelalder","region":"Vest-Europa","emoji":"👑","image":"","info":"Den frankiske kongen Chlodvig beseiret rivaler i Gallia og bygget opp et mektig frankisk rike. Frankerriket fikk stor betydning for Europas politiske utvikling i middelalderen.","tags":["Chlodvig","Frankerriket","frankere"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"muhammed-dor-632","bankId":"N16","year":632,"displayYear":"632","title":"Muhammed dør og den islamske ekspansjonen begynner","difficulty":2,"category":"Religion","period":"Middelalderen","region":"Midtøsten","emoji":"☪️","image":"","info":"Da Muhammed døde i 632, hadde islam fått en sterk stilling på Den arabiske halvøy. Under de første kalifene ekspanderte det muslimske riket raskt utenfor Arabia.","tags":["Muhammed","islam","kalifatet"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"karl-den-store-keiser-800","bankId":"N17","year":800,"displayYear":"800","title":"Karl den store krones til keiser","difficulty":3,"category":"Politikk","period":"Middelalderen","region":"Vest-Europa","emoji":"👑","image":"","info":"Paven kronet Karl den store til keiser i Roma. Kroningen markerte et nytt vestlig keiserdømme og styrket forbindelsen mellom frankisk kongemakt og kirken.","tags":["Karl den store","keiser","Frankerriket"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"tysk-romerske-riket-962","bankId":"N18","year":962,"displayYear":"962","title":"Det tysk-romerske riket blir til","difficulty":3,"category":"Politikk","period":"Middelalderen","region":"Sentral-Europa","emoji":"🦅","image":"","info":"Otto 1. ble kronet til keiser i Roma. Dette regnes ofte som begynnelsen på Det tysk-romerske riket, som besto i ulike former fram til 1806.","tags":["Det tysk-romerske riket","Otto 1","keiser"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"vinland-ca-1000","bankId":"N19","year":1000,"displayYear":"ca. 1000","title":"Norrøne ferder når Nord-Amerika/Vinland","difficulty":1,"category":"Utforskning","period":"Vikingtid","region":"Nord-Atlanteren","emoji":"⛵","image":"","info":"Norrøne sjøfarere fra Grønland nådde områder i Nord-Amerika rundt år 1000. Arkeologiske funn på Newfoundland viser at norrøne mennesker oppholdt seg der.","tags":["Vinland","Leiv Eiriksson","Nord-Amerika"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","topics":["norsk-historie"]},
  {"id":"store-skisma-1054","bankId":"N20","year":1054,"displayYear":"1054","title":"Det store skisma: østkirken og vestkirken skilles","difficulty":3,"category":"Religion","period":"Middelalderen","region":"Europa og Middelhavet","emoji":"⛪","image":"","info":"I 1054 ble bruddet mellom den latinske kirken i vest og den greske kirken i øst tydelig. Splittelsen utviklet seg til skillet mellom den romersk-katolske og den ortodokse kirken.","tags":["skisma","katolsk","ortodoks"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"normannerne-erobrer-england-1066","bankId":"N21","year":1066,"displayYear":"1066","title":"Normannerne erobrer England","difficulty":2,"category":"Krig og konflikt","period":"Middelalderen","region":"England","emoji":"🏹","image":"","info":"Vilhelm Erobreren beseiret den engelske kongen Harald Godwinson i slaget ved Hastings. Normannernes seier endret den engelske eliten, språket og styringssystemet.","tags":["1066","normannere","Hastings"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"forste-korstog-1096-1099","bankId":"N22","year":1096,"displayYear":"1096–1099","title":"Det første korstoget","difficulty":2,"category":"Krig og konflikt","period":"Middelalderen","region":"Middelhavet og Midtøsten","emoji":"🛡️","image":"","info":"Europeiske korsfarere dro mot Midtøsten og erobret Jerusalem i 1099. Etterpå ble flere korsfarerstater opprettet i området.","tags":["korstog","Jerusalem","middelalderen"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":1096,"end":1099}},
  {"id":"mongolene-invaderer-europa-1241","bankId":"N23","year":1241,"displayYear":"1241","title":"Mongolene invaderer Polen, Ungarn og Böhmen","difficulty":3,"category":"Krig og konflikt","period":"Middelalderen","region":"Øst- og Sentral-Europa","emoji":"🐎","image":"","info":"Mongolske styrker rykket langt inn i Europa og slo flere europeiske hærer. Invasjonen viste hvor langt det mongolske imperiets militære makt rakk.","tags":["mongoler","Europa","invasjon"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"mali-riket-blomstring-1250-1450","bankId":"N24","year":1250,"displayYear":"ca. 1250–1450","title":"Mali-rikets blomstringstid","difficulty":3,"category":"Politikk","period":"Middelalderen","region":"Vest-Afrika","emoji":"🪙","image":"","info":"Mali-riket ble en viktig makt i Vest-Afrika og kontrollerte sentrale handelsruter for blant annet gull og salt. Byer som Timbuktu utviklet seg til viktige handels- og kunnskapssentre.","tags":["Mali-riket","Timbuktu","Vest-Afrika"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":1250,"end":1450}},
  {"id":"hundrearskrigen-1337-1453","bankId":"N25","year":1337,"displayYear":"1337–1453","title":"Hundreårskrigen mellom England og Frankrike","difficulty":3,"category":"Krig og konflikt","period":"Middelalderen","region":"Vest-Europa","emoji":"⚔️","image":"","info":"England og Frankrike kjempet en lang serie kriger om territorier og den franske kronen. Frankrike gikk til slutt seirende ut av konflikten.","tags":["Hundreårskrigen","England","Frankrike"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":1337,"end":1453}},
  {"id":"svartedauden-europa-1347","bankId":"N26","year":1347,"displayYear":"1347","title":"Svartedauden kommer til Europa","difficulty":1,"category":"Samfunn","period":"Middelalderen","region":"Europa","emoji":"⚫","image":"","info":"Pesten nådde Europa i 1347 og spredte seg raskt. En svært stor del av Europas befolkning døde, noe som fikk omfattende sosiale og økonomiske følger.","tags":["svartedauden","pest","Europa"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"ming-dynastiet-1368","bankId":"N27","year":1368,"displayYear":"1368","title":"Ming-dynastiet kommer til makten i Kina","difficulty":3,"category":"Politikk","period":"Middelalderen","region":"Kina","emoji":"🐉","image":"","info":"Mongolenes Yuan-dynasti mistet makten, og Ming-dynastiet overtok styret i Kina. Ming-perioden ble preget av sterk sentralmakt, handel og store byggeprosjekter.","tags":["Ming-dynastiet","Kina","dynasti"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"inkariket-ca-1400","bankId":"N28","year":1400,"displayYear":"ca. 1400","title":"Inkaene bygger opp en stormakt i Sør-Amerika","difficulty":3,"category":"Politikk","period":"Middelalderen","region":"Sør-Amerika","emoji":"🦙","image":"","info":"Inkaene utvidet sitt rike fra Andesområdet og bygget opp et omfattende statsapparat, veinett og skattesystem. På 1400-tallet ble riket den dominerende makten i store deler av Andesfjellene.","tags":["Inkariket","inka","Andes"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"konstantinopel-faller-1453","bankId":"N29","year":1453,"displayYear":"1453","title":"Konstantinopel erobres av osmanene","difficulty":3,"category":"Krig og konflikt","period":"Senmiddelalderen","region":"Østlige Middelhav","emoji":"🕌","image":"","info":"Den osmanske sultanen Mehmet 2. erobret Konstantinopel. Erobringen gjorde slutt på Det bysantinske riket og byen ble et viktig sentrum i Det osmanske riket.","tags":["Konstantinopel","osmanene","Bysants"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"columbus-amerika-1492","bankId":"N30","year":1492,"displayYear":"1492","title":"Kristoffer Columbus når Amerika","difficulty":1,"category":"Utforskning","period":"Tidlig nytid","region":"Atlanterhavet og Amerika","emoji":"⛵","image":"","info":"Columbus krysset Atlanterhavet i spansk tjeneste og nådde øyer i Karibia. Reisen innledet en langvarig europeisk kolonisering og kontakt mellom verdensdelene.","tags":["Columbus","Amerika","oppdagelsesreiser"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"vasco-da-gama-india-1498","bankId":"N31","year":1498,"displayYear":"1498","title":"Vasco da Gama når India sjøveien","difficulty":2,"category":"Utforskning","period":"Tidlig nytid","region":"Europa, Afrika og India","emoji":"🧭","image":"","info":"Den portugisiske sjøfareren Vasco da Gama seilte rundt Afrika og nådde India. Sjøveien ble viktig for Portugals handel og ekspansjon i Indiahavet.","tags":["Vasco da Gama","India","Portugal"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"luther-95-teser-1517","bankId":"N32","year":1517,"displayYear":"1517","title":"Martin Luther offentliggjør de 95 tesene","difficulty":3,"category":"Religion","period":"Tidlig nytid","region":"Tyskland","emoji":"📜","image":"","info":"Martin Luther kritiserte blant annet avlatshandelen i den katolske kirken. Konflikten som fulgte bidro til reformasjonen og framveksten av protestantiske kirker.","tags":["Martin Luther","reformasjonen","95 teser"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"forste-jordomseiling-1519-1522","bankId":"N33","year":1519,"displayYear":"1519–1522","title":"Den første jordomseilingen","difficulty":1,"category":"Utforskning","period":"Tidlig nytid","region":"Verden","emoji":"🌍","image":"","info":"En ekspedisjon ledet først av Ferdinand Magellan seilte vestover og fullførte den første dokumenterte jordomseilingen. Magellan selv døde før ekspedisjonen kom tilbake til Europa.","tags":["Magellan","jordomseiling","oppdagelsesreiser"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":1519,"end":1522}},
  {"id":"pizarro-inkariket-1531","bankId":"N34","year":1531,"displayYear":"1531","title":"Pizarro begynner erobringen av Inkariket","difficulty":3,"category":"Krig og konflikt","period":"Tidlig nytid","region":"Sør-Amerika","emoji":"⚔️","image":"","info":"Francisco Pizarro og spanske styrker innledet erobringen av Inkariket. Sykdommer, interne konflikter og militærmakt bidro til at det store riket raskt ble svekket.","tags":["Pizarro","Inkariket","Spania"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"spanske-armada-1588","bankId":"N35","year":1588,"displayYear":"1588","title":"Den spanske armada blir beseiret","difficulty":3,"category":"Krig og konflikt","period":"Tidlig nytid","region":"Vest-Europa","emoji":"⛵","image":"","info":"En stor spansk flåte forsøkte å støtte en invasjon av England. Angrep, dårlig vær og logistiske problemer førte til at felttoget mislyktes.","tags":["spanske armada","England","Spania"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"tokugawa-shogunatet-1603","bankId":"N36","year":1603,"displayYear":"1603","title":"Tokugawa-shogunatet etableres i Japan","difficulty":3,"category":"Politikk","period":"Tidlig nytid","region":"Japan","emoji":"🏯","image":"","info":"Tokugawa Ieyasu ble shogun og etablerte et styre som skulle vare i mer enn 250 år. Perioden var preget av politisk stabilitet og streng kontroll over samfunnet.","tags":["Tokugawa","Japan","shogunat"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"jamestown-1607","bankId":"N37","year":1607,"displayYear":"1607","title":"Jamestown grunnlegges","difficulty":3,"category":"Kolonisering","period":"Tidlig nytid","region":"Nord-Amerika","emoji":"🏘️","image":"","info":"Jamestown i Virginia ble den første varige engelske bosetningen i det som senere ble USA. Kolonien fikk store problemer i starten, men overlevde.","tags":["Jamestown","Virginia","kolonisering"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"trettiarskrigen-1618-1648","bankId":"N38","year":1618,"displayYear":"1618–1648","title":"Trettiårskrigen","difficulty":2,"category":"Krig og konflikt","period":"Tidlig nytid","region":"Europa","emoji":"⚔️","image":"","info":"Trettiårskrigen begynte som en konflikt i Det tysk-romerske riket og utviklet seg til en omfattende europeisk krig. Store områder i Sentral-Europa ble hardt rammet.","tags":["Trettiårskrigen","Europa","religionskrig"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":1618,"end":1648}},
  {"id":"england-konstitusjonelt-monarki-1688","bankId":"N39","year":1688,"displayYear":"1688","title":"England blir et konstitusjonelt monarki","difficulty":2,"category":"Politikk","period":"Tidlig nytid","region":"England","emoji":"👑","image":"","info":"Den ærerike revolusjonen førte til at kongemakten ble tydeligere underlagt parlamentet og lovene. Utviklingen styrket det konstitusjonelle monarkiet i England.","tags":["England","parlament","konstitusjonelt monarki"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"sjuarskrigen-1756-1763","bankId":"N40","year":1756,"displayYear":"1756–1763","title":"Sjuårskrigen","difficulty":2,"category":"Krig og konflikt","period":"1700-tallet","region":"Europa og koloniene","emoji":"🌍","image":"","info":"Sjuårskrigen ble utkjempet både i Europa og i kolonier rundt om i verden. Storbritannias seier styrket landets posisjon som en ledende kolonimakt.","tags":["Sjuårskrigen","Storbritannia","kolonier"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":1756,"end":1763}},
  {"id":"industrielle-revolusjon-1770-arene","bankId":"N41","year":1770,"displayYear":"1770-årene","title":"Den industrielle revolusjonen begynner i England","difficulty":1,"category":"Teknologi","period":"Industrialisering","region":"England","emoji":"🏭","image":"","info":"Nye maskiner, energikilder og fabrikker endret produksjon og arbeidsliv. Industrialiseringen startet tidlig i Storbritannia og spredte seg senere til andre deler av verden.","tags":["industriell revolusjon","fabrikker","England"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":1770,"end":1779}},
  {"id":"usa-uavhengighet-1776","bankId":"N42","year":1776,"displayYear":"1776","title":"USA erklærer seg uavhengig","difficulty":1,"category":"Politikk","period":"Opplysningstiden","region":"Nord-Amerika","emoji":"🇺🇸","image":"","info":"Tretten britiske kolonier vedtok uavhengighetserklæringen og erklærte seg uavhengige av Storbritannia. Krigen mot britene fortsatte fram til 1783.","tags":["USA","uavhengighet","1776"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"haiti-selvstendig-1804","bankId":"N43","year":1804,"displayYear":"1804","title":"Haiti blir selvstendig","difficulty":3,"category":"Politikk","period":"1800-tallet","region":"Karibia","emoji":"🇭🇹","image":"","info":"Etter et stort slaveopprør og langvarig krig ble Haiti uavhengig av Frankrike. Landet ble den første selvstendige staten i Latin-Amerika som sprang ut av et vellykket slaveopprør.","tags":["Haiti","uavhengighet","slaveopprør"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"napoleon-beseires-wienkongressen-1815","bankId":"N44","year":1815,"displayYear":"1815","title":"Napoleon beseires og Wienkongressen samles","difficulty":2,"category":"Politikk","period":"1800-tallet","region":"Europa","emoji":"🎖️","image":"","info":"Napoleon ble endelig beseiret ved Waterloo. Europas stormakter møttes samtidig i Wien for å reorganisere Europas grenser og skape en ny maktbalanse etter Napoleonskrigene.","tags":["Napoleon","Wienkongressen","Waterloo"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"slaveriet-forbys-britiske-kolonier-1833","bankId":"N45","year":1833,"displayYear":"1833","title":"Slaveriet forbys i de britiske koloniene","difficulty":2,"category":"Samfunn","period":"1800-tallet","region":"Det britiske imperiet","emoji":"⛓️","image":"","info":"Det britiske parlamentet vedtok en lov som avskaffet slaveriet i de fleste britiske koloniene. Gjennomføringen skjedde gradvis de følgende årene.","tags":["slaveri","Storbritannia","avskaffelse"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"hongkong-opiumskrigen-1842","bankId":"N46","year":1842,"displayYear":"1842","title":"Kina avstår Hongkong til Storbritannia etter opiumskrigen","difficulty":3,"category":"Krig og konflikt","period":"1800-tallet","region":"Kina","emoji":"🚢","image":"","info":"Etter den første opiumskrigen måtte Qing-Kina inngå Nanjingtraktaten. Hongkong ble avstått til Storbritannia og flere kinesiske havner ble åpnet for utenlandsk handel.","tags":["opiumskrigen","Hongkong","Kina"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"amerikanske-borgerkrigen-1861-1865","bankId":"N47","year":1861,"displayYear":"1861–1865","title":"Den amerikanske borgerkrigen","difficulty":2,"category":"Krig og konflikt","period":"1800-tallet","region":"USA","emoji":"⚔️","image":"","info":"Nordstatene og Sørstatene kjempet en blodig borgerkrig. Nordstatene vant, unionen ble bevart og slaveriet ble avskaffet i USA.","tags":["amerikanske borgerkrigen","USA","slaveri"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":1861,"end":1865}},
  {"id":"meiji-restaurasjonen-1868","bankId":"N48","year":1868,"displayYear":"1868","title":"Meiji-restaurasjonen begynner i Japan","difficulty":3,"category":"Politikk","period":"1800-tallet","region":"Japan","emoji":"🌸","image":"","info":"Keisermakten ble styrket og Tokugawa-shogunatet tok slutt. Japan satte i gang omfattende reformer og modernisering av stat, militær og økonomi.","tags":["Meiji","Japan","modernisering"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"suezkanalen-1869","bankId":"N49","year":1869,"displayYear":"1869","title":"Suezkanalen åpnes","difficulty":3,"category":"Teknologi","period":"1800-tallet","region":"Egypt","emoji":"🚢","image":"","info":"Suezkanalen skapte en direkte sjøvei mellom Middelhavet og Rødehavet. Reisen mellom Europa og Asia ble dermed betydelig kortere.","tags":["Suezkanalen","handel","Egypt"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"tyskland-samles-1871","bankId":"N50","year":1871,"displayYear":"1871","title":"Tyskland samles til ett keiserrike","difficulty":3,"category":"Politikk","period":"1800-tallet","region":"Tyskland","emoji":"🇩🇪","image":"","info":"Etter flere kriger ledet av Preussen ble de fleste tyske statene samlet i et nytt tysk keiserrike. Wilhelm 1. ble utropt til tysk keiser.","tags":["Tysklands samling","Bismarck","Preussen"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"berlinkonferansen-1884-1886","bankId":"N51","year":1884,"displayYear":"1884–1886","title":"Berlinkonferansen og kappløpet om Afrika","difficulty":3,"category":"Internasjonal politikk","period":"Imperialismen","region":"Afrika og Europa","emoji":"🌍","image":"","info":"Europeiske stormakter møttes i Berlin og laget regler for hvordan de kunne gjøre krav på områder i Afrika. Perioden ble fulgt av en rask europeisk kolonisering av store deler av kontinentet.","tags":["Berlinkonferansen","imperialisme","Afrika"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":1884,"end":1886}},
  {"id":"russiske-revolusjonen-1917","bankId":"N52","year":1917,"displayYear":"1917","title":"Den russiske revolusjonen","difficulty":2,"category":"Politikk","period":"Første verdenskrig","region":"Russland","emoji":"🚩","image":"","info":"Revolusjonene i 1917 førte til at tsaren mistet makten og at bolsjevikene tok kontroll senere samme år. Utviklingen la grunnlaget for Sovjetunionen.","tags":["russiske revolusjonen","bolsjeviker","Russland"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"borskrakket-1929","bankId":"N53","year":1929,"displayYear":"1929","title":"Børskrakket i New York utløser økonomisk verdenskrise","difficulty":1,"category":"Økonomi","period":"Mellomkrigstiden","region":"Verden","emoji":"📉","image":"","info":"Et kraftig fall på børsen i New York ble et symbol på starten på den store depresjonen. Arbeidsledighet og økonomisk nedgang rammet mange land i årene som fulgte.","tags":["børskrakket","1929","depresjonen"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"hitler-rikskansler-1933","bankId":"N54","year":1933,"displayYear":"1933","title":"Hitler blir rikskansler i Tyskland","difficulty":1,"category":"Politikk","period":"Mellomkrigstiden","region":"Tyskland","emoji":"🏛️","image":"","info":"Adolf Hitler ble utnevnt til rikskansler i januar 1933. Nazistene avviklet deretter raskt det demokratiske systemet og etablerte et diktatur.","tags":["Hitler","nazisme","Tyskland"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"andre-verdenskrig-begynner-1939","bankId":"N55","year":1939,"displayYear":"1939","title":"Andre verdenskrig begynner","difficulty":1,"category":"Krig og konflikt","period":"Andre verdenskrig","region":"Europa","emoji":"🪖","image":"","info":"Tyskland invaderte Polen 1. september 1939. Storbritannia og Frankrike erklærte kort tid etter krig mot Tyskland, og konflikten utviklet seg til en verdenskrig.","tags":["andre verdenskrig","1939","Polen"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"fn-opprettes-1945","bankId":"N56","year":1945,"displayYear":"1945","title":"FN opprettes","difficulty":1,"category":"Internasjonal politikk","period":"Etterkrigstiden","region":"Verden","emoji":"🇺🇳","image":"","info":"De forente nasjoner ble opprettet etter andre verdenskrig for å fremme internasjonalt samarbeid, fred og sikkerhet. Organisasjonen fikk sitt FN-paktgrunnlag i 1945.","tags":["FN","1945","internasjonalt samarbeid"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"india-pakistan-selvstendige-1947","bankId":"N57","year":1947,"displayYear":"1947","title":"India og Pakistan blir selvstendige","difficulty":2,"category":"Politikk","period":"Avkolonisering","region":"Sør-Asia","emoji":"🕊️","image":"","info":"Britisk India ble avviklet som koloni og delt i de selvstendige statene India og Pakistan. Delingen førte samtidig til omfattende vold og store folkeforflytninger.","tags":["India","Pakistan","avkolonisering"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"koreakrigen-1950-1953","bankId":"N58","year":1950,"displayYear":"1950–1953","title":"Koreakrigen","difficulty":2,"category":"Krig og konflikt","period":"Den kalde krigen","region":"Korea","emoji":"⚔️","image":"","info":"Nord-Korea invaderte Sør-Korea i 1950. Krigen trakk inn styrker ledet av USA under FN-flagg og kinesiske styrker, og endte med våpenhvile i 1953.","tags":["Koreakrigen","den kalde krigen","Korea"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":1950,"end":1953}},
  {"id":"sputnik-1957","bankId":"N59","year":1957,"displayYear":"1957","title":"Sputnik skytes opp","difficulty":2,"category":"Vitenskap og teknologi","period":"Den kalde krigen","region":"Verdensrommet","emoji":"🛰️","image":"","info":"Sovjetunionen sendte Sputnik 1 i bane som verdens første kunstige satellitt. Oppskytningen satte fart i romkappløpet mellom Sovjetunionen og USA.","tags":["Sputnik","romkappløpet","Sovjetunionen"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"berlinmuren-bygges-1961","bankId":"N60","year":1961,"displayYear":"1961","title":"Berlinmuren bygges","difficulty":1,"category":"Politikk","period":"Den kalde krigen","region":"Tyskland","emoji":"🧱","image":"","info":"Østtyske myndigheter stengte grensen gjennom Berlin og bygget en mur for å hindre folk i å flykte til Vest-Berlin. Muren ble et av den kalde krigens sterkeste symboler.","tags":["Berlinmuren","den kalde krigen","Tyskland"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"cubakrisen-1962","bankId":"N61","year":1962,"displayYear":"1962","title":"Cubakrisen","difficulty":2,"category":"Internasjonal politikk","period":"Den kalde krigen","region":"Cuba","emoji":"☢️","image":"","info":"USA oppdaget sovjetiske atomraketter på Cuba. I tretten dager sto USA og Sovjetunionen i en svært alvorlig konfrontasjon før en avtale ble nådd.","tags":["Cubakrisen","atomvåpen","den kalde krigen"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"vietnamkrigen-1965-1975","bankId":"N62","year":1965,"displayYear":"1965–1975","title":"Vietnamkrigen","difficulty":2,"category":"Krig og konflikt","period":"Den kalde krigen","region":"Sørøst-Asia","emoji":"🚁","image":"","info":"USA trappet kraftig opp sin militære innsats i Vietnam fra 1965. Krigen endte i 1975 da Nord-Vietnam og dets allierte tok kontroll over Sør-Vietnam.","tags":["Vietnamkrigen","USA","den kalde krigen"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt","yearRange":{"start":1965,"end":1975}},
  {"id":"tsjernobyl-1986","bankId":"N63","year":1986,"displayYear":"1986","title":"Tsjernobylulykken","difficulty":2,"category":"Samfunn","period":"Den kalde krigen","region":"Ukraina, Sovjetunionen","emoji":"☢️","image":"","info":"En reaktor ved kjernekraftverket i Tsjernobyl eksploderte og slapp ut store mengder radioaktivt materiale. Ulykken fikk alvorlige følger for mennesker og miljø i flere land.","tags":["Tsjernobyl","atomkraft","ulykke"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"apartheid-mandela-1994","bankId":"N64","year":1994,"displayYear":"1994","title":"Apartheid avskaffes og Nelson Mandela blir president","difficulty":2,"category":"Politikk","period":"Etter den kalde krigen","region":"Sør-Afrika","emoji":"🗳️","image":"","info":"Sør-Afrika gjennomførte sitt første nasjonale valg med allmenn stemmerett. Nelson Mandela ble president etter tiår med kamp mot apartheidsystemet.","tags":["apartheid","Nelson Mandela","Sør-Afrika"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"11-september-2001","bankId":"N65","year":2001,"displayYear":"2001","title":"Terrorangrepene 11. september","difficulty":1,"category":"Krig og konflikt","period":"2000-tallet","region":"USA","emoji":"🕯️","image":"","info":"Kaprede passasjerfly ble brukt i terrorangrep mot World Trade Center og Pentagon. Nesten 3000 mennesker ble drept, og angrepene fikk store internasjonale følger.","tags":["11. september","terror","USA"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"russland-annekterer-krim-2014","bankId":"N66","year":2014,"displayYear":"2014","title":"Russland annekterer Krim","difficulty":1,"category":"Krig og konflikt","period":"2000-tallet","region":"Ukraina","emoji":"🗺️","image":"","info":"Russland tok kontroll over Krimhalvøya og erklærte området innlemmet i Russland. Annekteringen ble fordømt av Ukraina og et stort flertall i FNs generalforsamling.","tags":["Krim","Ukraina","Russland"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"},
  {"id":"russland-invaderer-ukraina-2022","bankId":"N67","year":2022,"displayYear":"2022","title":"Russland invaderer Ukraina","difficulty":1,"category":"Krig og konflikt","period":"2000-tallet","region":"Ukraina","emoji":"⚔️","image":"","info":"Russland startet en fullskala invasjon av Ukraina 24. februar 2022. Krigen førte til omfattende kamper, ødeleggelser og store flyktningstrømmer.","tags":["Ukraina","Russland","2022"],"sourceLabel":"Store norske leksikon","sourceUrl":"https://snl.no/verdens_historie_-_oversikt"}
];
/* =========================================================
   REGLER FOR UPRESISE ÅRSTALL OG ÅRSSPENN
========================================================= */

/*
  acceptedYearRange brukes av spillmotoren når en hendelse
  ikke har ett eneste nøyaktig årstall.

  Dette er spillmessige toleranser – ikke et utsagn om at
  historikere nødvendigvis daterer hendelsen til hele intervallet.
*/

const APPROXIMATE_YEAR_RANGES = {

  // GAMLE KORT

  G1: {
    start: -10500,
    end: -9500
  },

  G2: {
    start: -3100,
    end: -2900
  },

  G16: {
    start: 1440,
    end: 1460
  },


  // NYE KORT

  N2: {
    start: -3150,
    end: -3050
  },

  N4: {
    start: -1750,
    end: -1650
  },

  N12: {
    start: 20,
    end: 40
  },

  N19: {
    start: 980,
    end: 1020
  },

  N28: {
    start: 1375,
    end: 1425
  }

};


/*
  Gå gjennom alle hendelsene.
*/

window.TIMELINE_EVENTS.forEach(event => {

  /*
    1. Kort som allerede har yearRange,
       f.eks. 1519–1522,
       får hele intervallet som godkjent svar.
  */

  if (
    event.yearRange &&
    Number.isFinite(event.yearRange.start) &&
    Number.isFinite(event.yearRange.end)
  ) {

    event.acceptedYearRange = {
      start: event.yearRange.start,
      end: event.yearRange.end
    };
  }


  /*
    2. Kort merket "ca." får det
       egendefinerte intervallet over.
  */

  const approximateRange =
    APPROXIMATE_YEAR_RANGES[event.bankId];


  if (approximateRange) {

    event.acceptedYearRange = {
      start: approximateRange.start,
      end: approximateRange.end
    };
  }

});


/* =========================================================
   SPESIALTILFELLE: "FØR 7000 F.KR."
========================================================= */

/*
  "Før 7000 f.Kr." har ikke ett naturlig eksakt svar.

  Derfor markerer vi kortet slik at game.js senere kan
  hoppe over dette kortet i Eksakt årstall og ±10 år.
*/

const jerikoEvent =
  window.TIMELINE_EVENTS.find(
    event => event.bankId === "N1"
  );


if (jerikoEvent) {

  jerikoEvent.skipYearGuess = true;
}
