create table if not exists public.round_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  points integer not null default 0 check (points >= 0),
  correct integer not null default 0 check (correct >= 0),
  wrong integer not null default 0 check (wrong >= 0),
  total integer not null check (total >= 0),
  mode text not null check (mode like '%:lives:all'),
  created_at timestamptz not null default now()
);

alter table public.round_results enable row level security;

create policy "Anyone can read leaderboard results"
  on public.round_results for select
  using (true);

create policy "Signed-in users can submit their own results"
  on public.round_results for insert
  with check (auth.uid() = user_id);

create index if not exists round_results_leaderboard_idx
  on public.round_results (total desc, wrong asc, correct desc, created_at asc);
